Addfile("src/luacembed.lua")
Addfile("src/extra.lua")
Addfile("src/globals.lua")
Addfile("src/modules.lua")
Addfile("src/embed/embed.lua")
Addfile("src/embed/luaembed.lua")
Addfile("src/embed/cembed.lua")
Addfile("src/generators/mainc_generator.lua")
Addfile("src/generators/lua_generator.lua")
Addfile("src/main.lua")


Generate_c_executable_output("darwin006.c")
os.execute("gcc darwin006.c -o  darwin006.o")
os.execute("mv darwin006.o /home/mateusmoutinho/Documentos/teste/darwin006.o")
