---@class DarwinProject
---@field lua_code any[] --DarwinFileStream or string
---@field c_code string[]
---@field c_calls string[]
---@field embed_data PrivateDarwinEmbed[]

---- methods
---@class DarwinProject
---@field embed_global fun(name:string,value:table | string | number |boolean | DarwinFileStream)
---@field add_lua_code fun(code:string)
---@field add_lua_file fun(src:string)
---@field generate_lua_complex fun(props:LuaGenerationComplexProps)
---@field generate_lua_code fun(props:LuaGenerationCodeProps):string
---@field generate_lua_file fun(props:LuaGenerationOutputProps)
